import type { ApplianceCategory, InventoryCategory } from './types';

export interface PresetAppliance {
  name: string;
  category: ApplianceCategory;
}

export interface PresetFood {
  name: string;
  category: InventoryCategory;
}

export const PRESET_APPLIANCES: PresetAppliance[] = [
  // Small appliances
  { name: 'Instant Pot', category: 'small_appliance' },
  { name: 'Air Fryer', category: 'small_appliance' },
  { name: 'Microwave', category: 'small_appliance' },
  { name: 'Stand Mixer', category: 'small_appliance' },
  { name: 'Hand Mixer', category: 'small_appliance' },
  { name: 'Blender', category: 'small_appliance' },
  { name: 'Food Processor', category: 'small_appliance' },
  { name: 'Toaster', category: 'small_appliance' },
  { name: 'Toaster Oven', category: 'small_appliance' },
  { name: 'Coffee Maker', category: 'small_appliance' },
  { name: 'Rice Cooker', category: 'small_appliance' },
  { name: 'Slow Cooker', category: 'small_appliance' },
  { name: 'Electric Kettle', category: 'small_appliance' },
  { name: 'Waffle Maker', category: 'small_appliance' },
  { name: 'Panini Press', category: 'small_appliance' },
  // Cooking
  { name: 'Cast Iron Skillet', category: 'cooking' },
  { name: 'Non-stick Skillet', category: 'cooking' },
  { name: 'Stainless Steel Pan', category: 'cooking' },
  { name: 'Wok', category: 'cooking' },
  { name: 'Dutch Oven', category: 'cooking' },
  { name: 'Saucepan', category: 'cooking' },
  { name: 'Stock Pot', category: 'cooking' },
  { name: 'Grill Pan', category: 'cooking' },
  { name: 'Roasting Pan', category: 'cooking' },
  // Baking
  { name: 'Sheet Pan', category: 'baking' },
  { name: 'Muffin Tin', category: 'baking' },
  { name: 'Loaf Pan', category: 'baking' },
  { name: 'Cake Pan', category: 'baking' },
  { name: 'Pie Dish', category: 'baking' },
  { name: 'Casserole Dish', category: 'baking' },
  { name: 'Rolling Pin', category: 'baking' },
  // Prep
  { name: "Chef's Knife", category: 'prep' },
  { name: 'Paring Knife', category: 'prep' },
  { name: 'Cutting Board', category: 'prep' },
  { name: 'Box Grater', category: 'prep' },
  { name: 'Peeler', category: 'prep' },
  { name: 'Can Opener', category: 'prep' },
  { name: 'Kitchen Shears', category: 'prep' },
  { name: 'Mandoline Slicer', category: 'prep' },
];

export const PRESET_FOODS: PresetFood[] = [
  // Proteins
  { name: 'Chicken Breast', category: 'proteins' },
  { name: 'Ground Beef', category: 'proteins' },
  { name: 'Eggs', category: 'proteins' },
  { name: 'Salmon', category: 'proteins' },
  { name: 'Shrimp', category: 'proteins' },
  { name: 'Tofu', category: 'proteins' },
  { name: 'Bacon', category: 'proteins' },
  { name: 'Ground Turkey', category: 'proteins' },
  { name: 'Canned Tuna', category: 'proteins' },
  { name: 'Pork Chops', category: 'proteins' },
  // Vegetables
  { name: 'Onion', category: 'vegetables' },
  { name: 'Garlic', category: 'vegetables' },
  { name: 'Bell Pepper', category: 'vegetables' },
  { name: 'Spinach', category: 'vegetables' },
  { name: 'Broccoli', category: 'vegetables' },
  { name: 'Tomato', category: 'vegetables' },
  { name: 'Potato', category: 'vegetables' },
  { name: 'Carrots', category: 'vegetables' },
  { name: 'Zucchini', category: 'vegetables' },
  { name: 'Mushrooms', category: 'vegetables' },
  { name: 'Celery', category: 'vegetables' },
  { name: 'Kale', category: 'vegetables' },
  { name: 'Corn', category: 'vegetables' },
  { name: 'Green Beans', category: 'vegetables' },
  // Fruits
  { name: 'Lemon', category: 'fruits' },
  { name: 'Lime', category: 'fruits' },
  { name: 'Banana', category: 'fruits' },
  { name: 'Apple', category: 'fruits' },
  { name: 'Avocado', category: 'fruits' },
  { name: 'Strawberries', category: 'fruits' },
  { name: 'Blueberries', category: 'fruits' },
  // Carbs
  { name: 'White Rice', category: 'carbs' },
  { name: 'Brown Rice', category: 'carbs' },
  { name: 'Pasta', category: 'carbs' },
  { name: 'Bread', category: 'carbs' },
  { name: 'All-Purpose Flour', category: 'carbs' },
  { name: 'Oats', category: 'carbs' },
  { name: 'Tortillas', category: 'carbs' },
  { name: 'Quinoa', category: 'carbs' },
  { name: 'Noodles', category: 'carbs' },
  // Dairy
  { name: 'Butter', category: 'dairy' },
  { name: 'Milk', category: 'dairy' },
  { name: 'Heavy Cream', category: 'dairy' },
  { name: 'Parmesan Cheese', category: 'dairy' },
  { name: 'Cheddar Cheese', category: 'dairy' },
  { name: 'Greek Yogurt', category: 'dairy' },
  { name: 'Sour Cream', category: 'dairy' },
  { name: 'Cream Cheese', category: 'dairy' },
  { name: 'Mozzarella', category: 'dairy' },
  // Pantry
  { name: 'Olive Oil', category: 'pantry' },
  { name: 'Vegetable Oil', category: 'pantry' },
  { name: 'Chicken Broth', category: 'pantry' },
  { name: 'Canned Tomatoes', category: 'pantry' },
  { name: 'Coconut Milk', category: 'pantry' },
  { name: 'Honey', category: 'pantry' },
  { name: 'Sugar', category: 'pantry' },
  { name: 'Brown Sugar', category: 'pantry' },
  { name: 'Baking Powder', category: 'pantry' },
  { name: 'Baking Soda', category: 'pantry' },
  { name: 'Cornstarch', category: 'pantry' },
  { name: 'Tomato Paste', category: 'pantry' },
  { name: 'Canned Chickpeas', category: 'pantry' },
  { name: 'Canned Black Beans', category: 'pantry' },
  // Spices
  { name: 'Salt', category: 'spices' },
  { name: 'Black Pepper', category: 'spices' },
  { name: 'Garlic Powder', category: 'spices' },
  { name: 'Onion Powder', category: 'spices' },
  { name: 'Cumin', category: 'spices' },
  { name: 'Paprika', category: 'spices' },
  { name: 'Smoked Paprika', category: 'spices' },
  { name: 'Oregano', category: 'spices' },
  { name: 'Chili Powder', category: 'spices' },
  { name: 'Cayenne Pepper', category: 'spices' },
  { name: 'Cinnamon', category: 'spices' },
  { name: 'Turmeric', category: 'spices' },
  { name: 'Italian Seasoning', category: 'spices' },
  { name: 'Red Pepper Flakes', category: 'spices' },
  { name: 'Bay Leaves', category: 'spices' },
  // Condiments
  { name: 'Ketchup', category: 'condiments' },
  { name: 'Mustard', category: 'condiments' },
  { name: 'Mayonnaise', category: 'condiments' },
  { name: 'Hot Sauce', category: 'condiments' },
  { name: 'Worcestershire Sauce', category: 'condiments' },
  { name: 'Sriracha', category: 'condiments' },
  { name: 'Soy Sauce', category: 'condiments' },
  { name: 'Fish Sauce', category: 'condiments' },
  { name: 'Apple Cider Vinegar', category: 'condiments' },
  { name: 'Balsamic Vinegar', category: 'condiments' },
];
